version: "2"
services:
  node:
    build: .
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    expose:
      - "8080"
    command: "npm start"
